version: "1"
services:
  - type: web
    name: searchapi
    runtime: docker
    repo: https://github.com/Pratyay360/searchapi
    plan: free
    dockerContext: .
    dockerfilePath: ./Containerfile
    autoDeployTrigger: commit
